language: julia

os:
  - linux
  - osx

julia:
  - 1.3
  - nightly

branches:
  only:
    - master

notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      script:
        - julia --project=docs/ docs/make.jl
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
      after_success: skip
