language: julia

os:
  - linux
  - osx

julia:
  - 1.3
  - nightly

addons:
  apt:
    packages:
      - python3-matplotlib

branches:
  only:
    - master

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("DiscretePredictors")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("DiscretePredictors")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
