language: julia

os:
  - linux
  - osx

julia:
  - 1.3
  - nightly

addons:
  apt:
    packages:
      - python3-matplotlib

branches:
  only:
    - master

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
  - julia --project -e 'using Pkg; Pkg.add("Coverage"); import VisAna; joinpath(dirname(pathof(VisAna)), ".."); using Coverage; Coveralls.submit(Coveralls.process_folder());'
  - julia --project -e 'using Pkg; Pkg.add("Coverage"); import VisAna; joinpath(dirname(pathof(VisAna)), ".."); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
